substitutions:
  _ENV: gs://h-07-450914_cloudbuild/pacer/.env
  _FIREBASE: gs://h-07-450914_cloudbuild/pacer/pacer.json

steps:
  # Step 1: Ambil file .env
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", "backend/.env"]

  # Step 2: Ambil file firebase credentials
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_FIREBASE}", "backend/pacer.json"]

  # Opsional: cek isi .env
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'cat backend/.env']

  # Step 3: Build image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/pacer", "."]

  # Step 4: Push image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/pacer"]

  # Step 5: Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "pacer",
        "--image", "gcr.io/$PROJECT_ID/pacer",
        "--timeout", "1000s",
        "--region", "us-central1",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1600s"
