substitutions:
  _ENV: gs://h-07-450914_cloudbuild/pacer/.env

steps:
  # Step 1: Mengambil file .env dari Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", "backend/.env"]
# Step 2: Build image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/pacer",
        "-f", "backend/Dockerfile",
        "backend"
      ]

  # Step 3: Push image ke Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend"]

  # Step 4: Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "backend",
        "--image", "gcr.io/$PROJECT_ID/backend",
        "--timeout", "1000s",
        "--port", "3000",
        "--region", "us-central1",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1600s"
